using System.Collections.Generic;public class Module{public string name, p1, p2, p3, p4, p5, p6, p7;public Module(string name,string p1,string p2,string p3,string p4,string p5,string p6,string p7){this.name=name;this.p1=p1;this.p2=p2;this.p3=p3;this.p4=p4;this.p5=p5;this.p6=p6;this.p7=p7;}public List<Module> ModuleList = new List<Module>();public void Generate(){
ModuleList.Add(new Module(@"❖","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"% Gary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"% Grey","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"...?","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"0","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"1000 Words","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"100 Levels of Defusal","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"101 Dalmatians","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"14","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"15 Mystic Lights","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"16 Coins","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"1D Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"21","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"3D Maze","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"3D Tunnels","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"3 LEDs","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"3x3 Grid","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"42","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"501","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"64","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"7","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"9-Ball","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"A Mistake","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"A>N<D","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Aa","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Abstract Sequences","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Accelerando","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Accumulation","No","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Addition","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Adjacent Letters","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Adventure Game","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Affine Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Air Traffic Controller","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alchemy","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Algebra","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Alien Filing Colors","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Alliances","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Alpha","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alpha-Bits","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alphabet","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alphabet Numbers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alphabet Tiles","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alphabetical Order","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Alphabetical Ruling","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Alphabetize","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"A Message","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Amnesia","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Anagrams","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Annoying Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Answering Can Be Fun","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Answering Questions","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Antichamber","Yes","No","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Arithmelogic","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Arrow Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ars Goetia Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Art Appreciation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"ASCII Art","No","Yes","Yes","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"ASCII Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Assembly Code","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Astrology","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Atbash Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Audio Keypad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Audio Morse","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"B-Machine","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Baba Is Who","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Baccarat","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Backgrounds","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Badugi","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bamboozled Again","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bamboozling Button","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bamboozling Button Grid","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bamboozling Time Keeper","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Bartending","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Bases","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Basic Morse","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Battleship","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Baybayin Words","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Beanboozled Again","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Beans","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Benedict Cumberbatch","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Big Circle","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Binary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Binary Grid","No","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Binary LEDs","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Binary Puzzle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Binary Tree","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Birthdays","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bitmaps","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Bitwise Operations","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Black Cipher","Yes","No","No","No","Yes","No","No"));
ModuleList.Add(new Module(@"Black Hole","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Blackjack","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Blind Alley","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Blind Arrows","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Blind Maze","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Blinkstop","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Block Stacks","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Blockbusters","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Bloxx","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Blue","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Blue Arrows","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Blue Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bob Barks","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Boggle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bomb Diffusal","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Bone Apple Tea","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boolean Keypad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boolean Math","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boolean Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Boolean Venn Diagram","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boolean Wires","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Boomdas","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boot Too Big","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boozleglyph Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"BoozleTalk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bottom Gear","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Boxing","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Braille","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Brainf---","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Brawler Database","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Breaktime","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Bridge","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Bridges","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"British Slang","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Broken Binary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Broken Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Broken Guitar Chords","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Broken Karaoke","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Brush Strokes","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Burger Alarm","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Burglar Alarm","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Burnout","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Busy Beaver","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Butterflies","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Button Grid","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Button Masher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Button Messer","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Button Order","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Button Sequence","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"BuzzFizz","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Caesar Cipher","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Caesar Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Caesar's Maths","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Calculus","No","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Calendar","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Capacitor Discharge","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Catchphrase","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cell Lab","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Censorship","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Chalices","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Challenge & Contact","No","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Chamber No. 5","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Character Codes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Character Shift","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cheap Checkout","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cheat Checkout","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cheep Checkout","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Chess","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Chicken Nuggets","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Chinese Counting","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Chinese Strokes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Chord Progressions","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Chord Qualities","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Christmas Presents","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Codenames","Yes","No","No","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"Coffeebucks","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color Addition","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color Braille","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color-Cycle Button","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Color Decoding","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Color Generator","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Color Hexagons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color Match","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color Math","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Color Morse","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color Numbers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Color One Two","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colored Buttons","No","Yes","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colored Hexabuttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colored Keys","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Colored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colored Switches","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colorful Dials","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Colorful Insanity","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colorful Madness","Yes","No","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Colour Catch","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colour Code","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Colour Flash","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Colour Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Combination Lock","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Command Prompt","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Common Sense","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Commuting","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Complex Keypad","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Complicated Buttons","Yes","No","No","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Complicated Wires","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Conditional Buttons","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Connected Monitors","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Connection Check","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Connection Device","No","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Constellations","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Co-op Harmony Sequence","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cookie Jars","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cooking","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cool Beans","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Coordinates","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Corners","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cosmic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Countdown","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Crackbox","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Crazy Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Crazy Talk With A K","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Creation","No","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cruel Binary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cruel Boolean Math","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cruel Boolean Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cruel Countdown","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cruel Digital Root","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cruel Garfield Kart","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cruel Keypads","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Cruel Match 'Em","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cruel Piano Keys","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cruel Stars","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Cruel Ten Seconds","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cryptic Cycle","No","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Cryptic Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Cryptography","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Currents","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Curriculum","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Cursed Double-Oh","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"D-CIPHER","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"D-CODE","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"D-CRYPT","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"DACH Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Daylight Directions","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Deaf Alley","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Deck Creating","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Decolored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Desert Bus","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Determinants","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"DetoNATO","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Devilish Eggs","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Dictation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Digisibility","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Digit String","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Digital Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Digital Clock","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Digital Dials","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Digital Grid","Yes","No","Yes","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Digital Root","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Dimension Disruption","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Directional Button","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Discolored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Disordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Divided Squares","Yes","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Divisible Numbers","Yes","No","Yes","No","No","No","No"));
ModuleList.Add(new Module(@"Dominoes","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Double Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Double Color","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Double Expert","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Double Listening","Yes","No","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Double-Oh","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Double Pitch","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Dr. Doctor","Yes","Yes","Yes","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"Dragon Energy","Yes","Yes","Yes","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Draw","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Dreamcipher","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Duck, Duck, Goose","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Dumb Waiters","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Dungeon","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Dungeon 2nd Floor","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Earthbound","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Echolocation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Edgework","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"egg","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Eight Pages","Yes","Yes","No","No","No","Yes","No"));
ModuleList.Add(new Module(@"Elder Futhark","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Elder Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Emoji Math","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Emotiguy Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Encrypted Dice","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Encrypted Equations","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Encrypted Hangman","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Encrypted Morse","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Encrypted Values","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Encryption Bingo","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"English Entries","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"English Test","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Entry Number Four","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Equations","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Equations X","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Error Codes","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Etterna","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"European Travel","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Even Or Odd","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Exoplanets","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Extended Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Factoring ","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Factory Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Fast Math","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Faulty Accelerando","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty Backgrounds","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Faulty Binary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty Butterflies","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty Chinese Counting","Yes","No","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Faulty Digital Root","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty RGB Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty Seven Segment Displays","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Faulty Sink","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Fencing","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Festive Piano Keys","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Fifteen","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Filibuster","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Find The Date","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Five Letter Words","No","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"FizzBuzz","Yes","No","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Flag Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Flags","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Flashing Lights","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Flash Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Flavor Text","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Flavor Text EX","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Flip The Coin","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Flower Patch","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Follow the Leader","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Following Orders","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Font Select","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Footnotes","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Foreign Exchange Rates","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Forget Any Color","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Forget Enigma","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Everything","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Infinity","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Forget It Not","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Me Not","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Forget Me Now","Yes","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Me Later","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Perspective","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget The Colors","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Forget Them All","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Forget This","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Forget Us Not","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Four-Card Monte","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Four Lights","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Frankenstein's Indicator","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Free Parking","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Friendship","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Fruits","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Functions","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Funny Numbers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Gadgetron Vendor","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Game of Life Cruel","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Game of Life Simple","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Garfield Kart","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Genetic Sequence","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Geometry Dash","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Gettin' Funky","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Gnomish Puzzle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Going Backwards","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Golf","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Goofy's Game","Yes","Yes","No","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Gradually Watermelon","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Graffiti Numbers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Graphic Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Gray Cipher","Yes","Yes","No","No","No","No","No"));
ModuleList.Add(new Module(@"Greek Calculus","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Greek Letter Grid","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Green Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Green Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Grid Matching","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Gridlock","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Grocery Store","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Gryphons","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Guess Who?","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Guitar Chords","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"h","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Harmony Sequence","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Heraldry","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Hereditary Base Notation","Yes","Yes","Yes","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"Hex To Decimal","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hexamaze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hieroglyphics","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hidden Colors","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Hide and Seek","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Higher Or Lower","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hill Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hinges","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hogwarts","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hold Ups","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Hole in One","No","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Homophones","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Horrible Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hot Potato","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"HTTP Response","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Human Resources","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hunting","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hyperactive Numbers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Hyperneedy","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ice Cream","Yes","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Iconic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Identifying Soulless","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Identity Parade","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"IKEA","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Increasing Indices","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Indigo Cipher","No","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Ingredients","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Insanagrams","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Insane Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Instructions","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"int##","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Integer Trees","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Intervals","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Iñupiaq Numerals","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"IPA","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jack Attack","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jackbox.TV","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jaden Smith Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jailbreak","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jellybeans","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jenga","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Johnson Solids","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Jukebox.WAV","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Jumble Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Just Numbers","Yes","Yes","Yes","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"Juxtacolored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Kanji","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"KayMazey Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Keep Clicking","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Keypad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Keypad Combinations","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Keypad Directionality","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Keypad Lock","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Keywords ","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Kilo Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Kim's Game","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Knob","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Know Your Way","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Kooky Keypad","No","Yes","No","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Krazy Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Kudosudoku","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Kugelblitz","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Kyudoku","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Langton's Ant","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Ladder Lottery","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Lasers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Laundry","Yes","Yes","No","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"LED Encryption","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"LED Grid","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"LED Math","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Left and Right","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"LEGOs","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Letter Keys","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Letter Layers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Life Iteration","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Light Bulbs","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Light Cycle","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Lights On","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lights Out","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lightspeed","No","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Lines of Code","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lion's Share","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Listening","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Literally Crying","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Literally Nothing","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lockpick Maze","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Logic","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Logic Gates","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Logic Statement","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Logical Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Logical Operators","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lombax Cubes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Long Beans","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Look and Say","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Loopover","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lousy Chess","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Lucky Dice","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Lunchtime","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Lying Indicators","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Lyrical Nonsense","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"M&Ms","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"M&Ns","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Mad Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mafia","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Mahjong","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Maintenance","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Malfunctions","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Manometers","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Marble Tumble","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Marco Polo","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Maritime Flags","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mashematics","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mastermind Cruel","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Mastermind Simple","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mastermind Restricted","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Masher The Bottun","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Masyu","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Match 'em","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Matchematics","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Math","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Matrices","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Maze Scrambler","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Maze³","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Mazematics","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mazery","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mechanus Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mega Man 2","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Melodic Message","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Melody Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Melody Sequencer","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Memorable Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mental Math","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Metamem","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Meter","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Micro-Modules","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Microcontroller","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Microphone","No","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Mindlock","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Minecraft Cipher","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Minecraft Parody","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Minecraft Survival","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mineseeker","Yes","Yes","No","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Minesweeper","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Misery Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mislocation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Misordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Modern Cipher","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Module Homework","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Module Listening","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Module Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Module Movements","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Module Rick","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Modules Against Humanity","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Modulo","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Modulus Manipulation","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Monsplode Trading Cards","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Monsplode, Fight!","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"More Code","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Morse Buttons","Yes","No","No","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Morse Code","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Morse Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Morse War","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Morse-A-Maze","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Morsematics","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Mortal Kombat","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Motion Sense","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mouse In The Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Multi-Colored Switches","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Multitask","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Murder","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Musher the Batten","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Musical Transposition","Yes","Yes","No","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Mystery Module","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Mystic Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Mystic Square","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"N&Ms","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"N&Ns","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Name Changer","No","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Natures","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Naughty or Nice","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Navinums","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"NeeDeez Nuts","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Needlessly Complicated Button","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Needy Flower Mash","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Needy Mrs Bob","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Needy Piano","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Negation ","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Negativity","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Neutralization","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Neutrinos","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Nomai","Yes","Yes","Yes","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"Nonogram","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not the Button","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Not Capacitor Discharge","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not Complicated Wires","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Keypad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Knob","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Memory","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not Morse Code","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"NOT NOT","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Simaze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Venting Gas","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Not Who's on First","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Wire Sequence","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Not Wiresword","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Number Nimbleness","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Number Pad","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Numbered Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Numbers","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"NumberWang","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Object Shows","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Odd Mod Out","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Odd One Out","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Old Fogey","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"OmegaDestroyer","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"OmegaForget","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"One Links to All","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Only Connect","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Orange Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Organization","No","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Orientation Cube","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"osu!","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Outrageous","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Painting","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Palindromes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Partial Derivatives","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Partitions","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Party Time","No","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Passcodes","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Passport Control","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Password Destroyer","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Password Generator","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Pattern Cube","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pattern Lock","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pay Respects","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Periodic Table","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Perplexing Wires","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Perspective Pegs","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Piano Keys","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Pickup Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pictionary","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pie","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pigpen Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pigpen Rotations","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Pitch Perfect","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pixel Art","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pixel Cipher","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Placeholder Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Planets","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Plant Identification","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Playfair Cipher","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Playfair Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Plug-Ins","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Plumbing","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Pocket Planes","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Poetry","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Point of Order","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Poker","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Polygons","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Polyhedral Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Pong","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Popufur","Yes","Yes","Yes","No","No","No","No"));
ModuleList.Add(new Module(@"Pow","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Press The Shape","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Press X","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Prime Checker","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Prime Encryption","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Prime Time","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Probing","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Purgatory","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Purple Arrrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Puzzword","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"QR Code","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Quaternions","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Quaver","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Question Mark","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Quick Arithmetic","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Quintuples","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Quiz Buzz","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Quote Crazy Talk End Quote","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Qwirkle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Radiator","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Raiding Temples","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Railway Cargo Loading","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rainbow Arrows","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Random Access Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Random Number Generator","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rapid Buttons","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rapid Subtraction","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Reaction","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Recolored Switches","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Recorded Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Red","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Red Arrows","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Red Buttons","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Red Cipher","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Red Herring","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Red Light Green Light","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Refill that Beer!","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Reflex","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Reformed Role Reversal","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"ReGret-B Filtering","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Regular Crazy Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Regular Hexpressions","No","Yes","Yes","No","No","No","No"));
ModuleList.Add(new Module(@"Remote Math","No","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Reordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Repo Selector","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Resistors","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Retirement","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Reverse Alphabetize","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Reverse Morse","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Reverse Polish Notation","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Reversed Edgework","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"RGB Arithmetic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"RGB Logic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"RGB Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"RGB Sequences","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rhythms","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Risky Wires","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Robot Programming","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rock-Paper-Scissors-Lizard-Spock","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Roger","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Role Reversal","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Roman Art","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Roman Numerals","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rotary Phone","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rotating Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rotten Beans","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Round Keypad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"RPS Judging","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rubik's Clock","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rubik's Cube","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Rules","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rune Match I","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rune Match II","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Rune Match III","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"S.E.T.","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Safety Safe","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Safety Square","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Saimoe Pad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Scavenger Hunt","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Schlag den Bomb","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Scripting","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Sea Bear Attacks","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sea Shells","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Security Council","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Semabols","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Semamorse","No","No","No","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Semaphore","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Sequences","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Settlers of KTaNE","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Seven Choose Four","Yes","No","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Seven Deadly Sins","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Seven Wires","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Shape Memory","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Shape Shift","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Shapes And Bombs","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Shell Game","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Shifted Maze","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Shifting Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Shikaku","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Shitass Says","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Shortcuts","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Shuffled Strings","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Signals","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Siffron","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Silenced Simon","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Silhouettes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Silly Slots","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Silo Authorization","Yes","Yes","Yes","Yes","No","Yes","Yes"));
ModuleList.Add(new Module(@"Simon Forgets","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Simon Literally Says","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Samples","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon Says","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon Scrambles","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Screams","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Simon Selects","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Sends","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Shrieks","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon Simons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Sings","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Simon Sounds","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Simon Speaks","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon Spins","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon Squawks","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Stages","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Stashes","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Simon States","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon Stops","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"Simon Stores","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Simon's on First","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon's Sequence","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon's Stages","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon's Star","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Simon's Ultimate Showdown","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"SimpSquad","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sink","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"SixTen","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Skewed Slots","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Skinny Wires","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Skyrim","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Snakes and Ladders","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Snap!","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Snooker","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Snowflakes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sonic & Knuckles","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sonic the Hedgehog","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sorting","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Sound Design","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Souvenir","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Space","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Space Invaders Extreme","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Spangled Stars","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Speak English","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Spelling Bee","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Spelling Buzzed","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Spinning Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Splitting The Loot","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Spot the Difference","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Square Button","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Stack'em","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Stained Glass","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Standard Button Masher","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Standard Crazy Talk","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Stars","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"State of Aggregation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sticky Notes","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Stock Images","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Street Fighter","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Strike/Solve","No","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Subscribe to Pewdiepie","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Subways","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Sueet Wall","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Sugar Skulls","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Superlogic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Switches","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Switching Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Symbol Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Symbolic Colouring","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Symbolic Coordinates","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Symbolic Password","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Symbolic Tasha","No","No","No","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Symmetries Of A Square","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"SYNC-125 [3]","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Synchronization","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Synesthesia","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Synonyms","Yes","Yes","No","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"T-Words","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Table Madness","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Taco Tuesday","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Tallordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tangrams","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tap Code","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Tasha Squeals","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Tax Returns","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Teal Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tech Support","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Telepathy","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Tell Me When","Yes","Yes","No","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Ten Seconds","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ten-Button Color Code","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Tennis","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Tenpins","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ternary Converter","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Terraria Quiz","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tetriamonds","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tetris","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tetravex","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Text Field","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Arena","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Bioscanner","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Black Page","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Block","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Bulb","No","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Button","No","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Calculator","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Clock","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Close Button","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Code","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Colored Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Console","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Crafting Table","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Cruel Duck","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The cRule","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Crystal Maze","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Cube","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Dealmaker","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Deck of Many Things","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Dials","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Digit","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Duck","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Exploding Pen","Yes","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Festive Jukebox","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Fidget Spinner","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Gamepad","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Gatekeeper","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Giant's Drink","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Great Void","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Hangover","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Heart","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Hexabutton","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Hidden Value","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The High Score","Yes","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Hypercube","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Hyperlink","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The iPhone","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Jack-O'-Lantern","No","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Jewel Vault","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Jukebox","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Kanye Encounter","Yes","No","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Labyrinth","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Legendre Symbol","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The London Underground","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Matrix","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Missing Letter","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Modkit","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Moon","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Necronomicon","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Number","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Number Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Overflow","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Pentabutton","Yes","No","Yes","No","No","No","No"));
ModuleList.Add(new Module(@"The Plunger Button","No","Yes","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Radio","Yes","No","Yes","Yes","No","No","Yes"));
ModuleList.Add(new Module(@"The Rule","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Samsung","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Screw","Yes","Yes","Yes","Yes","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Simpleton","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Sphere","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Stare","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Stock Market","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Stopwatch","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Sun","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Swan","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Switch","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"The Time Keeper","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Triangle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Triangle Button","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Troll","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"The Twin","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Ultracube","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Very Annoying Button","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The Wire","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"The Witness","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"The World's Largest Button","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Thinking Wires","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Third Base","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Thread The Needle","Yes","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Three Cryptic Steps","Yes","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tic-Tac-Toe","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Time Accumulation","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Time Signatures","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Timezone","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Timing is Everything","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Toolmods","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Toolneedy","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Toon Enough","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Topsy Turvy","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Totally Accurate Minecraft Simulator","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tower of Hanoi","Yes","Yes","Yes","No","Yes","No","No"));
ModuleList.Add(new Module(@"Towers","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Training Text","Yes","No","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Transmitted Morse","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Treasure Hunt","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Triamonds","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Triangle Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Tribal Council","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Turn The Key","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Turn The Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Turtle Robot","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Two Bits","Yes","Yes","No","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Two Persuasive Buttons","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Type Racer","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Typing Tutor","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Übermodule","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ultimate Cipher","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Ultimate Custom Night","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ultimate Cycle","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ultimate Tic Tac Toe","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Ultralogic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"UltraStores","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Uncolored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Uncolored Switches","No","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Unfair Cipher","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Unfair's Cruel Revenge","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Unfair's Revenge","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Unicode","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Unordered Keys","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Unown Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Unrelated Anagrams","Yes","Yes","Yes","No","Yes","No","Yes"));
ModuleList.Add(new Module(@"Updog","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"USA Maze","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"V","No","Yes","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Valves","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Varicolored Squares","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Vcrcs","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Vectors","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Venn Diagrams","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Venting Gas","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Vexillology","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Video Poker","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Vigenere Cipher","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Violet Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Visual Impairment","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wack Game of Life","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Waste Management","Yes","Yes","Yes","No","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Wavetapping","Yes","Yes","Yes","No","No","Yes","Yes"));
ModuleList.Add(new Module(@"Web Design","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Weird Al Yankovic","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Westeros","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"What's On Second","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"White Arrows","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"White Cipher","No","Yes","No","No","Yes","No","No"));
ModuleList.Add(new Module(@"Whiteout","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Who's On First","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Who's That Monsplode","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Widdershins","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wingdings","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wire Ordering","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wire Placement","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wire Sequence","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wire Spaghetti","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wires","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"Wolf, Goat, and Cabbage","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Wonder Cipher","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Word Scramble","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Word Search","Yes","No","No","No","No","No","Yes"));
ModuleList.Add(new Module(@"X-Ray","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"X01","Yes","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Yahtzee","Yes","No","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Yellow Arrows","Yes","Yes","Yes","Yes","Yes","Yes","Yes"));
ModuleList.Add(new Module(@"Yellow Cipher","No","No","Yes","No","No","No","Yes"));
ModuleList.Add(new Module(@"Yes and No","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Zoni","No","No","No","No","No","No","No"));
ModuleList.Add(new Module(@"Zoo","No","No","No","No","Yes","No","Yes"));
}}